// Mocks generated by Mockito 5.4.6 from annotations
// in semir_phone/integration_test/login_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:semir_phone/core/auth/auth_service.dart' as _i4;
import 'package:semir_phone/core/auth/token_storage.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserSession_0 extends _i1.SmartFake implements _i4.UserSession {
  _FakeUserSession_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorage extends _i1.Mock implements _i2.TokenStorage {
  MockTokenStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveTokens({
    required String? access,
    required String? refresh,
    required DateTime? expiry,
    required String? username,
    required List<String>? permissions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [],
          {
            #access: access,
            #refresh: refresh,
            #expiry: expiry,
            #username: username,
            #permissions: permissions,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateAccessToken(
    String? access,
    DateTime? expiry,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAccessToken,
          [
            access,
            expiry,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> readAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #readAccessToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> readRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #readRefreshToken,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> readUsername() => (super.noSuchMethod(
        Invocation.method(
          #readUsername,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<DateTime?> readAccessTokenExpiry() => (super.noSuchMethod(
        Invocation.method(
          #readAccessTokenExpiry,
          [],
        ),
        returnValue: _i3.Future<DateTime?>.value(),
      ) as _i3.Future<DateTime?>);

  @override
  _i3.Future<List<String>> readPermissions() => (super.noSuchMethod(
        Invocation.method(
          #readPermissions,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> saveBiometricEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #saveBiometricEnabled,
          [enabled],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> readBiometricEnabled() => (super.noSuchMethod(
        Invocation.method(
          #readBiometricEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserSession> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue: _i3.Future<_i4.UserSession>.value(_FakeUserSession_0(
          this,
          Invocation.method(
            #login,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i3.Future<_i4.UserSession>);

  @override
  _i3.Future<void> logout(String? refreshToken) => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [refreshToken],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> refresh(String? refreshToken) => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [refreshToken],
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
}
