# Generated by Django 6.0.2 on 2026-02-09 04:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_id', models.CharField(db_index=True, max_length=1000)),
                ('id_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('birthday_month', models.IntegerField(blank=True, null=True)),
                ('vip_grade', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(max_length=1000)),
                ('phone', models.CharField(db_index=True, max_length=1000)),
                ('race', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, max_length=1000, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('city_state', models.CharField(blank=True, max_length=1000, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('contact_address', models.TextField(blank=True, null=True)),
                ('registration_store', models.CharField(blank=True, max_length=1000, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['vip_id', 'phone'], name='App_custome_vip_id_7c9a8b_idx'), models.Index(fields=['registration_date'], name='App_custome_registr_4bfb38_idx')],
                'unique_together': {('vip_id', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('shop_id', models.CharField(max_length=1000)),
                ('shop_name', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('bu', models.CharField(blank=True, max_length=1000, null=True)),
                ('sales_date', models.DateField(db_index=True)),
                ('vip_id', models.CharField(db_index=True, max_length=1000)),
                ('vip_name', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tag_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_customer_transaction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rounding', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='App.customer')),
            ],
            options={
                'ordering': ['sales_date', 'invoice_number'],
                'indexes': [models.Index(fields=['vip_id', 'sales_date'], name='App_salestr_vip_id_c170df_idx'), models.Index(fields=['sales_date'], name='App_salestr_sales_d_249f97_idx')],
            },
        ),
    ]
