# Generated by Django 6.0.2 on 2026-02-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=1000, null=True)),
                ('creator', models.CharField(blank=True, max_length=1000, null=True)),
                ('document_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('coupon_id', models.CharField(db_index=True, max_length=1000)),
                ('face_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('used', models.IntegerField(default=0)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('using_shop', models.CharField(blank=True, max_length=1000, null=True)),
                ('using_date', models.DateField(blank=True, null=True)),
                ('push', models.CharField(blank=True, max_length=1000, null=True)),
                ('member_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('member_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('member_phone', models.CharField(blank=True, max_length=1000, null=True)),
                ('docket_number', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['coupon_id'], name='App_coupon_coupon__7e6b3d_idx'), models.Index(fields=['docket_number'], name='App_coupon_docket__b14bbf_idx'), models.Index(fields=['using_date'], name='App_coupon_using_d_56a1ee_idx'), models.Index(fields=['used'], name='App_coupon_used_6964f5_idx')],
            },
        ),
    ]
