# Generated by Django 6.0.2 on 2026-02-21 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNVCustomer',
            fields=[
                ('customer_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('membership_level', models.CharField(blank=True, max_length=50, null=True)),
                ('points_balance', models.IntegerField(default=0)),
                ('total_points_earned', models.IntegerField(default=0)),
                ('total_points_spent', models.IntegerField(default=0)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'CNV Customer',
                'verbose_name_plural': 'CNV Customers',
                'db_table': 'cnv_customers',
                'ordering': ['-last_synced_at'],
                'indexes': [models.Index(fields=['customer_code'], name='cnv_custome_custome_a44ad1_idx'), models.Index(fields=['phone'], name='cnv_custome_phone_3161f6_idx'), models.Index(fields=['-last_synced_at'], name='cnv_custome_last_sy_a8b2eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CNVOrder',
            fields=[
                ('order_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('customer_code', models.CharField(db_index=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('order_date', models.DateTimeField(db_index=True)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('store_code', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('points_earned', models.IntegerField(default=0)),
                ('points_used', models.IntegerField(default=0)),
                ('items', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'CNV Order',
                'verbose_name_plural': 'CNV Orders',
                'db_table': 'cnv_orders',
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['-order_date'], name='cnv_orders_order_d_0403ea_idx'), models.Index(fields=['customer_code', '-order_date'], name='cnv_orders_custome_fe23cb_idx'), models.Index(fields=['store_code', '-order_date'], name='cnv_orders_store_c_1f0ed3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CNVSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('customers', 'Customers'), ('orders', 'Orders'), ('full', 'Full Sync')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CNV Sync Log',
                'verbose_name_plural': 'CNV Sync Logs',
                'db_table': 'cnv_sync_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['sync_type', 'status'], name='cnv_sync_lo_sync_ty_083b9f_idx'), models.Index(fields=['-started_at'], name='cnv_sync_lo_started_7375d6_idx')],
            },
        ),
    ]
