# Generated by Django 6.0.2 on 2026-02-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_cnvcustomer_cnvorder_cnvsynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnvsynclog',
            name='checkpoint_updated_at',
            field=models.DateTimeField(blank=True, help_text='Latest updated_at from fetched records - used as starting point for next sync', null=True),
        ),
        migrations.AddIndex(
            model_name='cnvsynclog',
            index=models.Index(fields=['sync_type', '-checkpoint_updated_at'], name='cnv_sync_lo_sync_ty_bb8cde_idx'),
        ),
    ]
