# Generated by Django 6.0.2 on 2026-02-27 11:35
# CUSTOM: Drop and recreate CNVCustomer table due to primary key change

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_cnvsynclog_checkpoint_updated_at_and_more'),
    ]

    operations = [
        # Step 1: Drop the old table completely
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS cnv_customers;',
            reverse_sql='SELECT 1;'  # Irreversible
        ),
        
        # Step 2: Create the new table with correct structure
        migrations.CreateModel(
            name='CNVCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnv_id', models.BigIntegerField(db_index=True, unique=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday_day', models.IntegerField(blank=True, null=True)),
                ('birthday_month', models.IntegerField(blank=True, null=True)),
                ('birthday_year', models.IntegerField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('physical_card_code', models.CharField(blank=True, max_length=100, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('exp_points', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_spending', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('level_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('used_points', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cnv_created_at', models.DateTimeField(blank=True, null=True)),
                ('cnv_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'CNV Customer',
                'verbose_name_plural': 'CNV Customers',
                'db_table': 'cnv_customers',
                'ordering': ['-last_synced_at'],
            },
        ),
        
        # Step 3: Add indexes
        migrations.AddIndex(
            model_name='cnvcustomer',
            index=models.Index(fields=['cnv_id'], name='cnv_custome_cnv_id_9b23ab_idx'),
        ),
        migrations.AddIndex(
            model_name='cnvcustomer',
            index=models.Index(fields=['phone'], name='cnv_custome_phone_a1b2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='cnvcustomer',
            index=models.Index(fields=['level_name'], name='cnv_custome_level_n_f7b5af_idx'),
        ),
        migrations.AddIndex(
            model_name='cnvcustomer',
            index=models.Index(fields=['-last_synced_at'], name='cnv_custome_last_sy_d4e5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='cnvcustomer',
            index=models.Index(fields=['-cnv_updated_at'], name='cnv_custome_cnv_upd_a4734a_idx'),
        ),
    ]