# Generated by Django 6.0.2 on 2026-02-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_cnvcustomer_cnv_custome_custome_a44ad1_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cnvcustomer',
            new_name='cnv_custome_phone_3161f6_idx',
            old_name='cnv_custome_phone_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='cnvcustomer',
            new_name='cnv_custome_last_sy_a8b2eb_idx',
            old_name='cnv_custome_last_sy_d4e5f6_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='used_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='used_points_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
