# Generated by Django 6.0.2 on 2026-03-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_cnv_custome_phone_a1b2c3_idx_cnv_custome_phone_3161f6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnvcustomer',
            name='zalo_app_created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cnvcustomer',
            name='zalo_app_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cnvcustomer',
            name='zalo_oa_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cnvsynclog',
            name='sync_type',
            field=models.CharField(choices=[('customers', 'Customers'), ('orders', 'Orders'), ('full', 'Full Sync'), ('zalo_sync', 'Zalo Sync')], max_length=20),
        ),
    ]
