# Generated by Django 6.0.2 on 2026-03-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0008_role_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CouponCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("prefix", models.CharField(max_length=100)),
                ("detail", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
