# Generated by Django 6.0.2 on 2026-03-28 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_couponcampaign_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopNameTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shop Name Title',
                'verbose_name_plural': 'Shop Name Titles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ShopNameAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=1000, unique=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='App.shopnametitle')),
            ],
            options={
                'verbose_name': 'Shop Name Alias',
                'verbose_name_plural': 'Shop Name Aliases',
                'ordering': ['alias'],
            },
        ),
    ]
