# Generated by Django 6.0.2 on 2026-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_cnvcustomer_cnv_created_at_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cnvcustomer',
            new_name='cnv_custome_cnv_cre_247f84_idx',
            old_name='cnv_customer_created_idx',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='using_shop',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_store',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='shop_name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
