# Generated by Django 6.0.2 on 2026-05-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_add_shop_name_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('shop_id', models.CharField(db_index=True, max_length=100)),
                ('shop_name', models.CharField(db_index=True, max_length=200)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('product_code', models.CharField(db_index=True, max_length=200)),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('product_name_vn', models.CharField(blank=True, max_length=500)),
                ('barcode', models.CharField(db_index=True, max_length=100)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('season', models.CharField(blank=True, db_index=True, max_length=10)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('category_l1', models.CharField(blank=True, max_length=100)),
                ('category_l2', models.CharField(blank=True, max_length=100)),
                ('category_l3', models.CharField(blank=True, max_length=100)),
                ('tag_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inventory_qty', models.IntegerField(default=0)),
                ('in_transit_qty', models.IntegerField(default=0)),
                ('total_qty', models.IntegerField(default=0)),
                ('tag_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tag_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='VND', max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['shop_name', 'brand'], name='App_invento_shop_na_727f50_idx'), models.Index(fields=['year', 'season'], name='App_invento_year_5f7b7c_idx'), models.Index(fields=['sku', 'shop_id'], name='App_invento_sku_a05a9f_idx')],
                'unique_together': {('shop_id', 'product_code')},
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=200)),
                ('shop_id', models.CharField(db_index=True, max_length=100)),
                ('shop_name', models.CharField(db_index=True, max_length=200)),
                ('sales_date', models.DateField(db_index=True)),
                ('sales_time', models.TimeField(blank=True, null=True)),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('product_code', models.CharField(max_length=200)),
                ('product_name', models.CharField(blank=True, max_length=500)),
                ('barcode', models.CharField(db_index=True, max_length=100)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('season', models.CharField(blank=True, db_index=True, max_length=10)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('category_l1', models.CharField(blank=True, max_length=100)),
                ('category_l2', models.CharField(blank=True, max_length=100)),
                ('category_l3', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('fact_retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settlement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tag_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tag_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('vat_rate', models.CharField(blank=True, max_length=20)),
                ('salesmen', models.CharField(blank=True, db_index=True, max_length=200)),
                ('salesmen_code', models.CharField(blank=True, max_length=100)),
                ('promotion', models.CharField(blank=True, max_length=500)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='App.salestransaction', to_field='invoice_number')),
            ],
            options={
                'indexes': [models.Index(fields=['sales_date', 'brand'], name='App_saledet_sales_d_a29131_idx'), models.Index(fields=['sales_date', 'shop_id'], name='App_saledet_sales_d_091ab5_idx'), models.Index(fields=['year', 'season', 'brand'], name='App_saledet_year_af1d0a_idx'), models.Index(fields=['sku', 'brand'], name='App_saledet_sku_8d922b_idx'), models.Index(fields=['salesmen', 'sales_date'], name='App_saledet_salesme_78508c_idx')],
                'unique_together': {('invoice_number', 'barcode', 'size')},
            },
        ),
    ]
