# Generated by Django 6.0.2 on 2026-05-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_inventorysnapshot_saledetail'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='saledetail',
            index=models.Index(fields=['sales_date', 'shop_name'], name='App_saledet_sales_d_ceb7fd_idx'),
        ),
    ]
