# Generated by Django 6.0.2 on 2026-05-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_saledetail_shop_name_date_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saledetail',
            unique_together={('invoice_number', 'product_code')},
        ),
    ]
