# Generated by Django 6.0.2 on 2026-06-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_product_campaign'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saledetail',
            unique_together={('invoice_number', 'product_code', 'barcode')},
        ),
    ]
