# Generated by Django 6.0.2 on 2026-06-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_saledetail_unique_add_barcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saledetail',
            unique_together=set(),
        ),
    ]
