# Generated by Django 6.0.2 on 2026-07-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_saledetail_remove_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_id',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
