# Generated by Django 6.0.2 on 2026-08-29 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_shop_group_trigram_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipSnapshotBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('auto', 'Automatic'), ('manual_import', 'Manual Backfill Import')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('row_count', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_id', models.CharField(max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('grade', models.CharField(max_length=20)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registration_store', models.CharField(blank=True, max_length=1000)),
                ('annual_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('annual_purchase_count', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('grade_changed_at', models.DateField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='App.membershipsnapshotbatch')),
            ],
        ),
        migrations.AddIndex(
            model_name='membershipsnapshotbatch',
            index=models.Index(fields=['source', 'snapshot_date'], name='App_members_source_9fe460_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipsnapshot',
            index=models.Index(fields=['batch', 'grade'], name='App_members_batch_i_f5cc97_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipsnapshot',
            index=models.Index(fields=['vip_id'], name='App_members_vip_id_414100_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipsnapshot',
            index=models.Index(fields=['batch', 'registration_store'], name='App_members_batch_i_6ae995_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membershipsnapshot',
            unique_together={('batch', 'vip_id', 'phone')},
        ),
    ]
