# Generated by Django 6.0.2 on 2026-08-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_membershipsnapshotbatch_membershipsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnvorder',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
