# Generated by Django 5.2.17 on 2026-09-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_membership_json_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGradeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_id', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('last_grade_change_date', models.DateField(blank=True, null=True)),
                ('change_direction', models.CharField(blank=True, choices=[('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], max_length=10)),
                ('simulated_grade', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('mismatch', 'Formula Mismatch'), ('no_data', 'No Transaction Data')], db_index=True, max_length=20)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('as_of_date', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='App_custome_status_26956c_idx')],
            },
        ),
    ]
