# Generated by Django 5.2.17 on 2026-09-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_customergradeprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergradeprogress',
            name='next_check_date',
            field=models.DateField(blank=True, help_text="The customer's NEXT scheduled downgrade anniversary check date (App/analytics/grade_simulation.py's simulate_one_customer() 4th return value, next_check_date). NULL when current_grade is Member/No Grade (no downgrade floor to check). NOT simply last_grade_change_date + 365 days -- a customer who has passed one or more prior annual checks without an actual grade change has next_check_date further out than that, since the check recurs every 365 days from the LAST CHECK, not the last change. Used to compute 'purchases needed to avoid downgrade' against the customer's TRUE upcoming check window, and shown directly in the Customer Tier Progress table as the expected downgrade review date.", null=True),
        ),
    ]
