"""
Django settings for SemirDashboard project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Security
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "SAMEORIGIN"
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Session security
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

    # Session timeout (24 hours)
    SESSION_COOKIE_AGE = 86400
    SESSION_SAVE_EVERY_REQUEST = True  # Auto-refresh session
    SESSION_EXPIRE_AT_BROWSER_CLOSE = False

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST", "db"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "CONN_MAX_AGE": 600,  # Keep connections alive for 10 minutes
        }
    }

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "App",
    "django_apscheduler",
    # SemirPhone API layer (Sprint 0)
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",       # Must be before CommonMiddleware
    "App.middleware.RequestIDMiddleware",           # Request ID for log correlation
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SemirDashboard.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SemirDashboard.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Category label language: 'VI' = show "中文 (Tiếng Việt)", 'ZH' = Chinese only
CATEGORY_LANG = os.environ.get("CATEGORY_LANG", "VI")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB

LOGIN_URL = "/login/"  # Fix 404 redirect
LOGIN_REDIRECT_URL = "/"  # After login go to home
LOGOUT_REDIRECT_URL = "/login/"  # After logout go to login

# ============================================================================
# CNV LOYALTY API CONFIGURATION
# ============================================================================

# CNV API Credentials
# IMPORTANT: Update these with your actual credentials
CNV_USERNAME = "danthanhtran@semir.com"  # Replace with actual username
CNV_PASSWORD = "***REMOVED***"  # Replace with actual password

# CNV API URLs
CNV_API_BASE_URL = "https://apis.cnvloyalty.com"
CNV_SSO_URL = "https://id.cnv.vn"

# Cache configuration — Redis in production, LocMem in dev
_REDIS_URL = os.getenv("REDIS_URL")
if _REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": _REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
                "CONNECTION_POOL_KWARGS": {"max_connections": 20},
                "SOCKET_CONNECT_TIMEOUT": 5,
                "SOCKET_TIMEOUT": 5,
            },
            "KEY_PREFIX": "semir",
            "TIMEOUT": 600,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "semir-cache",
            "TIMEOUT": 600,
            "OPTIONS": {"MAX_ENTRIES": 500},
        }
    }

# ============================================================================
# DJANGO APSCHEDULER CONFIGURATION
# ============================================================================

# APScheduler settings
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds

# ============================================================================
# LOGGING CONFIGURATION
# Structured JSON logs written to logs/ directory (rotating files).
# app.log    — general app events (views, services, uploads)
# cnv_sync.log — CNV sync events (separate file for easy filtering)
# errors.log — all ERROR+ events (all loggers)
# Admin log viewer: /admin-logs/ (superuser only)
# ============================================================================
LOGS_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {
            "()": "App.logging_utils.RequestIDFilter",
        },
    },
    "formatters": {
        # Human-readable for console
        "verbose": {
            "format": "[{levelname}] {asctime} {name} req={request_id} step={step} — {message}",
            "style": "{",
        },
        # Machine-readable structured JSON — one object per line
        "json": {
            "()": "App.logging_utils.JsonFormatter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["request_id"],
            "level": "INFO",
        },
        # General app log (views, services, uploads)
        "app_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "app.log"),
            "maxBytes": 10485760,   # 10 MB
            "backupCount": 5,
            "formatter": "json",
            "filters": ["request_id"],
            "level": "INFO",
        },
        # CNV sync log (separate file for easier filtering)
        "cnv_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "cnv_sync.log"),
            "maxBytes": 10485760,
            "backupCount": 5,
            "formatter": "json",
            "filters": ["request_id"],
            "level": "INFO",
        },
        # All ERROR+ across every logger
        "error_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_DIR, "errors.log"),
            "maxBytes": 10485760,
            "backupCount": 5,
            "formatter": "json",
            "filters": ["request_id"],
            "level": "ERROR",
        },
    },
    "loggers": {
        # CNV module — dedicated file + errors
        "App.cnv": {
            "handlers": ["console", "cnv_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        # All other App code — app file + errors
        "App": {
            "handlers": ["console", "app_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        # APScheduler background jobs
        "django_apscheduler": {
            "handlers": ["console", "app_file"],
            "level": "INFO",
            "propagate": False,
        },
        # Django 4xx/5xx request errors
        "django.request": {
            "handlers": ["console", "error_file"],
            "level": "WARNING",
            "propagate": False,
        },
        # Root — WARNING+ to console only (Django internals, third-party)
        "": {
            "handlers": ["console"],
            "level": "WARNING",
        },
    },
}

# ============================================================================
# DJANGO REST FRAMEWORK — SemirPhone JSON API (Sprint 0)
# ============================================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "EXCEPTION_HANDLER": "App.api.views.custom_exception_handler",
}

# ============================================================================
# SIMPLE JWT CONFIGURATION
# ============================================================================

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    # Single-use refresh tokens — rotate on every refresh, blacklist old ones.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ============================================================================
# CORS — Allow mobile app origins (native apps don't send CORS, but web admin
# console on the same domain may call the API from a browser).
# ============================================================================

CORS_ALLOW_ALL_ORIGINS = False
_cors_raw = os.getenv("CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_raw.split(",") if o.strip()]
CORS_ALLOW_CREDENTIALS = True

# In development, allow localhost origins for browser-based testing.
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
